in:
  type: file
  path_prefix: example/data.tsv
  parser:
    type: csv
    delimiter: "\t"
    charset: UTF-8
    newline: CRLF
    null_string: 'NULL'
    skip_header_lines: 1
    comment_line_marker: '#'
    columns:
      - {name: time,  type: timestamp, format: "%Y-%m-%d"}
      - {name: id, type: long}
      - {name: name, type: string}
      - {name: score, type: double}
      - {name: json_payload, type: string}

filters:
  - type: json_key
    column: json_payload
    nested_keys_delimiter: "."
    add_keys:
      - {key: xxxxx, value: {"aaa": "xxxx"}}
      - {key: profile.like_words.1, value: ["aaa", 1]}
    drop_keys:
      - {key: point}
      - {key: profile.anniversary.et}
      - {key: profile.like_words.2}

out:
  type: stdout

